import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React, { forwardRef } from 'react'

import { StyledButton } from './Button.styles'

export const Button = forwardRef(({
  children,
  className,
  onClick,
  variant,
  ...restOfProps
}, ref) => {
  return (
    <StyledButton
      className={className}
      onClick={onClick}
      ref={ref}
      variant={variant}
      {...pick(restOfProps)}
    >
      {children}
    </StyledButton>
  )
})

Button.displayName = 'Button'

Button.propTypes = {
  /**
   * Component children
   */
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]),

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * onClick event
   */
  onClick: PropTypes.func,

  /**
   * Different types of button styles
   */
  variant: PropTypes.oneOf(['primary', 'secondary']),

  /**
   * Styled system props
   */
  ...propTypes.color,
  ...propTypes.grid,
  ...propTypes.layout,
  ...propTypes.space
}

Button.defaultProps = {
  variant: 'primary'
}
