import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { StyledSearchField } from './SearchField.styles'

export const SearchField = ({
  className,
  onChange,
  placeholder,
  value,
  ...restOfProps
}) => {
  return (
    <StyledSearchField
      onChange={onChange}
      placeholder={placeholder}
      type='search'
      value={value}
      {...pick(restOfProps)}
    />
  )
}

SearchField.propTypes = {
  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * onChange event
   */
  onChange: PropTypes.func,

  /**
   * Input placeholder text
   */
  placeholder: PropTypes.string,

  /**
   * Input default values
   */
  value: PropTypes.string,

  /**
   * Styled system props
   */
  ...propTypes.layout,
  ...propTypes.space
}

SearchField.defaultProps = {
  value: ''
}
