import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { Box } from 'components/Box'
import { StyledSearchField, StyledSearchFieldLabel } from './SearchField.styles'

export const SearchField = ({
  className,
  id,
  label,
  onChange,
  placeholder,
  value,
  ...restOfProps
}) => {
  return (
    <Box className={className} {...pick(restOfProps)}>
      <StyledSearchFieldLabel htmlFor={id}>
        {label}
      </StyledSearchFieldLabel>
      <StyledSearchField
        id={id}
        onChange={onChange}
        placeholder={placeholder}
        type='search'
        value={value}
      />
    </Box>
  )
}

SearchField.propTypes = {
  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Unique id that is used to reference a field using <label>
   */
  id: PropTypes.string,

  /**
   * Label used to define a field
   */
  label: PropTypes.string,

  /**
   * onChange event
   */
  onChange: PropTypes.func,

  /**
   * Input placeholder text
   */
  placeholder: PropTypes.string,

  /**
   * Input default values
   */
  value: PropTypes.string,

  /**
   * Styled system props
   */
  ...propTypes.layout,
  ...propTypes.space
}

SearchField.defaultProps = {
  value: ''
}
