import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React, { useEffect, useRef, useState } from 'react'

import { Image } from 'components/Image'
import { StyledUserAvatar } from './UserAvatar.styles'

export const UserAvatar = ({ alt, className, src, ...restOfProps }) => {
  const avatarRef = useRef(null)
  const [display, setDisplay] = useState(false)

  /**
   * Lazy load images
   */
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      if (entries[0] && entries[0].isIntersecting) {
        setDisplay(true)
      }
    })

    observer.observe(avatarRef.current)

    return () => observer.unobserve(avatarRef.current)
  }, [avatarRef, avatarRef.current])

  return (
    <StyledUserAvatar
      className={className}
      ref={avatarRef}
      {...pick(restOfProps)}
    >
      {display && (
        <Image
          alt={alt}
          position='absolute'
          top={0}
          left={0}
          src={src}
          width='100%'
        />
      )}
    </StyledUserAvatar>
  )
}

UserAvatar.propTypes = {
  /**
   * Alt tag used to describe image when it fails to load
   */
  alt: PropTypes.string,

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Image path
   */
  src: PropTypes.string,

  /**
   * Styled system props
   */
  ...propTypes.layout,
  ...propTypes.position,
  ...propTypes.space
}
